create database employ;
use employ;
create table school(id int primary key,name varchar(20),age int);
desc school;
insert into school values(1,"uday",12),(2,"kiran",13);
select*from school;
alter table school add marks int;
desc school;
alter table school drop marks;
desc school;
alter table school add marks int;
alter table school add sub varchar(20);
desc school;
update school set marks=120 where id =1;
update school set sub="tel" where id=1;
update school set marks =150 where id=2;
update school set sub="hin" where id=2;
select id from school where id=1 and sub="tel";
select name from school where id=2 and sub="hin";
select * from school;